### ISSUE TITLE
Is this derived from the Java Intergalactics?

### ISSUE THREAD

**Issue by rm5248** [pents90/Intergalactics#1]
As the title says, is this derived from the Java version of Intergalactics?  I've been looking for the code for a while and stumbled upon this repo; the wayback machine at least says it was originally created by John Watkinson, and I wasn't sure if you're the same person.

If the code for the Java version of IGX still exists I would be interested  in seeing it; I have the original igx.jar but that doesn't have the server code in it and the reverse-engineered/decompiled Java code is a little hard to work with.

**Comment by Betalord** [comment]
You can actually find the original IGX source code here:
https://sourceforge.net/projects/igx/
I'm working on a "spiritual successor" to it, called Supergalactix. I wasn't able to find the original author though.

**Comment by pents90** [comment]
Hey, I am John Watkinson, the original creator of IGX. This was just an experiment in Node.js, so there's not much here. As Betalord says, you can find the original in that sourceforge project. The "original version by Moonman" download is the original IGX. However, I must confess that I wrote it more than 20 years(!) ago, and I was not a very good programmer back then. The code is straight-up awful. Probably better to do a clean-room rewrite then to delve into that trash, ha.

**Comment by rm5248** [comment]
Thanks for that; I did manage to download the original source(somehow I missed the original source file on Sourceforge, possibly because it doesn't show up under files).  I do have it working, albeit it does need some hand holding to get running properly.  If you're interested, I do have my version up on github: https://github.com/rm5248/Intergalactics

Anyway, thanks for the game!  I feel like messing around with that code because it's a bit of a fun challenge to bring it up to modern standards while still keeping it compatible. ;)
